services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --legacy-watch
    environment:
      NODE_ENV: development
      PORT: 5000
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8080}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
